version: '3'
services:
  api:
    build: .
    command: ["npx", "nodemon", "-L", "--watch", "src", "src/app.js"]
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - API_PORT=3000
      - JWT_SECRET=10b1346b75e107cc522ee6ad440d409e
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/craft-folio-gotchi
      - FRONT_END_URI=http://localhost
      - FIREBASE_SERVER_KEY=AAAAmrisMMY:APA91bFI1Y4NJW5uju81qN1X-tXhtH7UVL-rMvxvVNBOS83i6WKP8HavG5lm69A2DvPpcl0woWCx_bM_PC_hyVjBSWNQNRea4OceLaJA9Ogh6lI0ljL753m1j9T4vfXbAamnAVkumirxa_GmXDZ5cbdoAD2WcJYfHg
      - FIREBASE_SENDER_URI=https://fcm.googleapis.com/fcm/send
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    container_name: craft-folio-gotchi-api
  mongo:
    image: mongo:3.6
    expose:
      - "27017"
    ports:
      - "27017:27017"
    container_name: craft-folio-gotchi-mongo
