apiVersion: v1
kind: Service
metadata:
  name: craft-folio-gotchi-api
  labels:
    name: craft-folio-gotchi-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 'http'
      name: 'http'
  selector:
    name: craft-folio-gotchi-api
