apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craft-folio-gotchi-api
  labels:
    name: craft-folio-gotchi-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: craft-folio-gotchi-api
    spec:
      containers:
      - name: craft-folio-gotchi-api
        image: gcr.io/craft-folio-gotchi-207711/api:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "150m"
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: production
        - name: API_PORT
          value: '3000'
        - name: MONGO_CONNECTION_STRING
          value: mongodb://craft-folio-gotchi-mongo:27017/craft-folio-gotchi
        - name: JWT_SECRET
          value: 10b1346b75e107cc522ee6ad440d409e
        - name: FRONT_END_URI
          value: http://35.241.37.46
        - name: FIREBASE_SERVER_KEY
          value: AAAAmrisMMY:APA91bFI1Y4NJW5uju81qN1X-tXhtH7UVL-rMvxvVNBOS83i6WKP8HavG5lm69A2DvPpcl0woWCx_bM_PC_hyVjBSWNQNRea4OceLaJA9Ogh6lI0ljL753m1j9T4vfXbAamnAVkumirxa_GmXDZ5cbdoAD2WcJYfHg
        - name: FIREBASE_SENDER_URI
          value: https://fcm.googleapis.com/fcm/send
