---
apiVersion: v1
kind: Service
metadata:
  name: craft-folio-gotchi-mongo
  labels:
    name: craft-folio-gotchi-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: craft-folio-gotchi-mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: craft-folio-gotchi-mongo
spec:
  serviceName: "craft-folio-gotchi-mongo"
  replicas: 1
  template:
    metadata:
      labels:
        name: craft-folio-gotchi-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: craft-folio-gotchi-mongo
          image: mongo:3.4.6
          command:
            - mongod
            - "--smallfiles"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: craft-folio-gotchi-mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: craft-folio-gotchi-mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
